In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv("batter_analysis.csv")
df = df.iloc[:, 1:]

C:\Users\anekant.jain\AppData\Local\Temp\ipykernel_3996\1575714554.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("batter_analysis.csv")


In [31]:
team = "Royal Challengers Bangalore"

In [32]:
df.head()

match_id   season       city        date match_type player_of_match  \
0    335982  2007/08  Bangalore  2008-04-18     League     BB McCullum   
1    335982  2007/08  Bangalore  2008-04-18     League     BB McCullum   
2    335982  2007/08  Bangalore  2008-04-18     League     BB McCullum   
3    335982  2007/08  Bangalore  2008-04-18     League     BB McCullum   
4    335982  2007/08  Bangalore  2008-04-18     League     BB McCullum   

                   venue                        team1                  team2  \
0  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders   
1  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders   
2  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders   
3  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders   
4  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders   

                   toss_winner  ...   bowler  non_striker batsman_runs  \
0  Royal Challengers Bangalore  ...  P Kumar  BB McCullum            0   
1  Royal Challengers Bangalore  ...  P Kumar   SC Ganguly            0   
2  Royal Challengers Bangalore  ...  P Kumar   SC Ganguly            0   
3  Royal Challengers Bangalore  ...  P Kumar   SC Ganguly            0   
4  Royal Challengers Bangalore  ...  P Kumar   SC Ganguly            0   

   extra_runs  total_runs  extras_type is_wicket player_dismissed  \
0           1           1      legbyes         0              NaN   
1           0           0          NaN         0              NaN   
2           1           1        wides         0              NaN   
3           0           0          NaN         0              NaN   
4           0           0          NaN         0              NaN   

  dismissal_kind fielder  
0            NaN     NaN  
1            NaN     NaN  
2            NaN     NaN  
3            NaN     NaN  
4            NaN     NaN  

[5 rows x 36 columns]

In [61]:
df['inning'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 60182 entries, 0 to 60181
Series name: inning
Non-Null Count  Dtype
--------------  -----
60182 non-null  int64
dtypes: int64(1)
memory usage: 470.3 KB


### Batting

In [33]:
batter_df = df[((df['toss_winner'] != team) & (df['toss_decision'] == 'bat') & (df['inning'] == 2)) | 
                      ((df['toss_winner'] != team) & (df['toss_decision'] == 'field') & (df['inning'] == 1)) | 
                      ((df['toss_winner'] == team) & (df['toss_decision'] == 'field') & (df['inning'] == 2)) | 
                      ((df['toss_winner'] == team) & (df['toss_decision'] == 'bat') & (df['inning'] == 1))]

In [34]:
batter_df.over.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
batter_df.ball.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
batter_df['extras_type'].unique()

array([nan, 'wides', 'legbyes', 'noballs', 'byes'], dtype=object)

In [37]:
fours_total = batter_df[batter_df['batsman_runs'] == 4].groupby(['batter'])['batsman_runs'].count().reset_index()
fours_total = fours_total.sort_values(by='batsman_runs', ascending=False).head(10)
fours_total.rename(columns={'batsman_runs': 'total_fours'}, inplace=True)
fours_total

batter  total_fours
109         V Kohli          706
6    AB de Villiers          362
19         CH Gayle          249
31     F du Plessis          156
41        JH Kallis          127
32       GJ Maxwell          114
75         PA Patel           98
80         R Dravid           97
23       D Padikkal           95
47       KD Karthik           82

In [38]:
four_inning = batter_df[batter_df['batsman_runs'] == 4].groupby(['batter', 'match_id'])['batsman_runs'].count().reset_index()
four_inning = four_inning.sort_values(by='batsman_runs', ascending=False).head(10)
four_inning.rename(columns={'batsman_runs': 'total_fours'}, inplace=True)
four_inning

batter  match_id  total_fours
60    AB de Villiers    829795           19
1078         V Kohli   1359544           13
202         CH Gayle    598027           13
1082         V Kohli   1422137           12
752       RM Patidar   1312198           12
87    AB de Villiers   1136611           12
1000         V Kohli    980999           12
1077         V Kohli   1359539           12
254       D Padikkal   1216499           12
962          V Kohli    598048           11

In [39]:
sixes_total = batter_df[batter_df['batsman_runs'] == 6].groupby(['batter'])['batsman_runs'].count().reset_index()
sixes_total = sixes_total.sort_values(by='batsman_runs', ascending=False).head(10)
sixes_total.rename(columns={'batsman_runs': 'total_sixes'}, inplace=True)
sixes_total

batter  total_sixes
90         V Kohli          273
14        CH Gayle          239
3   AB de Villiers          238
24    F du Plessis           70
25      GJ Maxwell           69
67      RM Patidar           54
36      KD Karthik           53
43     LRPL Taylor           31
69      RV Uthappa           30
99    Yuvraj Singh           28

In [40]:
sixes_inning = batter_df[batter_df['batsman_runs'] == 6].groupby(['batter', 'match_id'])['batsman_runs'].count().reset_index()
sixes_inning = sixes_inning.sort_values(by='batsman_runs', ascending=False).head(10)
sixes_inning.rename(columns={'batsman_runs': 'total_sixes'}, inplace=True)
sixes_inning

batter  match_id  total_sixes
148        CH Gayle    598027           17
142        CH Gayle    548372           13
49   AB de Villiers    980987           12
167        CH Gayle    829785           12
732        WG Jacks   1426283           10
125        CH Gayle    501244            9
745    Yuvraj Singh    734005            9
145        CH Gayle    598008            9
52   AB de Villiers   1082598            9
663         V Kohli    980999            8

In [41]:
highest_score = batter_df.groupby(['batter'])['batsman_runs'].sum().reset_index()
highest_score_sorted = highest_score.sort_values(by='batsman_runs', ascending=False).head(10)
highest_score_sorted

batter  batsman_runs
138         V Kohli          8004
7    AB de Villiers          4491
22         CH Gayle          3163
40     F du Plessis          1636
42       GJ Maxwell          1266
53        JH Kallis          1132
59       KD Karthik           937
102        R Dravid           898
29       D Padikkal           884
108      RM Patidar           799

In [42]:
highest_score = batter_df.groupby(['batter', 'match_id'])['batsman_runs'].sum().reset_index()
highest_score_sorted = highest_score.sort_values(by='batsman_runs', ascending=False).head(10)

balls_faced = batter_df[(batter_df.extras_type != 'wides')].groupby(['match_id', 'batter'])['ball'].count().reset_index()
highest_score_with_balls = pd.merge(highest_score_sorted, balls_faced, on=['batter', 'match_id'], how='left')
highest_score_with_balls['strike_rate'] = round((highest_score_with_balls['batsman_runs'] / highest_score_with_balls['ball']) * 100, 2)
highest_score_with_balls

batter  match_id  batsman_runs  ball  strike_rate
0        CH Gayle    598027           175    66       265.15
1  AB de Villiers    829795           133    59       225.42
2  AB de Villiers    980987           129    52       248.08
3        CH Gayle    548372           128    62       206.45
4        CH Gayle    829785           117    57       205.26
5       MK Pandey    392236           114    73       156.16
6         V Kohli   1422137           113    72       156.94
7         V Kohli    980999           113    50       226.00
8      RM Patidar   1312198           112    54       207.41
9         V Kohli    980987           109    55       198.18

50s

In [43]:
fifty_scored = batter_df.groupby(['batter', 'match_id'])['batsman_runs'].sum().reset_index()
fifty_scored_sorted = fifty_scored[(fifty_scored.batsman_runs >= 50) & (fifty_scored.batsman_runs < 100)]
fifty_scored_sorted = fifty_scored_sorted.groupby('batter', as_index=False).count().sort_values('batsman_runs', ascending=False)
fifty_scored_sorted

batter  match_id  batsman_runs
31          V Kohli        55            55
0    AB de Villiers        37            37
4          CH Gayle        19            19
6      F du Plessis        15            15
7        GJ Maxwell        12            12
9         JH Kallis        10            10
24       RM Patidar         7             7
5        D Padikkal         6             6
29       TM Dilshan         5             5
21         PA Patel         4             4
11         KL Rahul         4             4
25       RV Uthappa         4             4
23         R Dravid         4             4
18           MM Ali         3             3
34     Yuvraj Singh         3             3
10       KD Karthik         3             3
20    Mandeep Singh         2             2
13     KP Pietersen         2             2
15      LRPL Taylor         2             2
2        Anuj Rawat         1             1
1          AJ Finch         1             1
17        MK Lomror         1             1
16       MA Agarwal         1             1
3         CA Pujara         1             1
8   Gurkeerat Singh         1             1
12        KM Jadhav         1             1
14        KS Bharat         1             1
26       SO Hetmyer         1             1
22        Q de Kock         1             1
19       MV Boucher         1             1
27       SP Goswami         1             1
30          TM Head         1             1
28        SS Tiwary         1             1
32         W Jaffer         1             1
33         WG Jacks         1             1

In [44]:
century_scored = batter_df.groupby(['batter', 'match_id'])['batsman_runs'].sum().reset_index()
century_scored_sorted = century_scored[(century_scored.batsman_runs >= 100)]
century_scored_sorted = century_scored_sorted.groupby('batter', as_index=False).count().sort_values('batsman_runs', ascending=False)
century_scored_sorted

batter  match_id  batsman_runs
5         V Kohli         8             8
1        CH Gayle         5             5
0  AB de Villiers         2             2
2      D Padikkal         1             1
3       MK Pandey         1             1
4      RM Patidar         1             1
6        WG Jacks         1             1

### Bowling

In [45]:
df.dismissal_kind.unique()

array([nan, 'caught', 'bowled', 'run out', 'retired hurt', 'stumped',
       'caught and bowled', 'lbw', 'hit wicket'], dtype=object)

In [46]:
df[['inning', 'team1', 'team2', 'toss_winner', 'toss_decision', 'bowler']].sample(5)

inning                        team1                        team2  \
34682       1               Mumbai Indians  Royal Challengers Bangalore   
5861        2  Royal Challengers Bangalore        Kolkata Knight Riders   
1007        1               Delhi Capitals  Royal Challengers Bangalore   
43650       1  Royal Challengers Bangalore        Kolkata Knight Riders   
59373       2  Royal Challengers Bangalore                 Punjab Kings   

                       toss_winner toss_decision          bowler  
34682  Royal Challengers Bangalore           bat  MJ McClenaghan  
5861   Royal Challengers Bangalore         field      BAW Mendis  
1007   Royal Challengers Bangalore         field   R Vinay Kumar  
43650  Royal Challengers Bangalore           bat      AD Russell  
59373                 Punjab Kings         field        WG Jacks

In [47]:
bowler_df = df[((df['toss_winner'] != team) & (df['toss_decision'] == 'bat') & (df['inning'] == 1)) | 
                ((df['toss_winner'] != team) & (df['toss_decision'] == 'field') & (df['inning'] == 2)) | 
                ((df['toss_winner'] == team) & (df['toss_decision'] == 'field') & (df['inning'] == 1)) | 
                ((df['toss_winner'] == team) & (df['toss_decision'] == 'bat') & (df['inning'] == 2))]

In [48]:
bowler_df['bowler'].unique()

array(['P Kumar', 'Z Khan', 'AA Noffke', 'JH Kallis', 'SB Joshi',
       'CL White', 'R Vinay Kumar', 'B Akhil', 'A Kumble', 'DW Steyn',
       'V Kohli', 'Abdur Razzak', 'JD Ryder', 'KP Pietersen',
       'LRPL Taylor', 'Pankaj Singh', 'KP Appanna', 'RE van der Merwe',
       'D du Preez', 'A Mithun', 'S Sriram', 'ND Doshi', 'DP Nannes',
       'DL Vettori', 'TM Dilshan', 'AUK Pathan', 'JJ van der Wath',
       'S Aravind', 'R Ninan', 'J Syed Mohammad', 'CH Gayle',
       'CK Langeveldt', 'AA Kazi', 'AB McDonald', 'M Muralitharan',
       'HV Patel', 'RR Bhatkal', 'P Parameswaran', 'JD Unadkat',
       'DT Christian', 'M Kartik', 'MC Henriques', 'RP Singh',
       'R Rampaul', 'MA Starc', 'JA Morkel', 'VR Aaron', 'YS Chahal',
       'AB Dinda', 'Yuvraj Singh', 'AN Ahmed', 'S Rana', 'SB Jakati',
       'SA Abbott', 'DJG Sammy', 'Iqbal Abdulla', 'D Wiese', 'AF Milne',
       'SR Watson', 'Parvez Rasool', 'KW Richardson', 'STR Binny',
       'T Shamsi', 'CJ Jordan', 'Sachin Baby', 'TS Mi

In [49]:
# name = "Yash Dayal"
name = "Mohammed Siraj"

In [50]:
dot_balls = bowler_df[(bowler_df.bowler == name) & (((bowler_df.extras_type == 'byes') | (bowler_df.extras_type == 'legbyes')) | (bowler_df.total_runs == 0))].shape[0]
total_runs = bowler_df[(bowler_df.bowler == name) & (bowler_df.extras_type != 'legbyes') & (bowler_df.extras_type != 'byes')]['total_runs'].sum() + bowler_df[(bowler_df.bowler == name) & (bowler_df.extras_type == 'noballs')]['batsman_runs'].sum()

In [51]:
total_balls = bowler_df.shape[0]
total_balls

30140

In [52]:
total_balls // 6

5023

In [53]:
bowler_df[bowler_df.bowler == name]['extras_type'].value_counts()

extras_type
wides      112
legbyes     37
noballs      8
byes         8
Name: count, dtype: int64

In [54]:
bowler_df[(bowler_df.bowler == name)].dismissal_kind.value_counts()

dismissal_kind
caught               58
bowled               16
lbw                   8
run out               2
retired hurt          1
caught and bowled     1
Name: count, dtype: int64

In [55]:
wickets_total = bowler_df[(bowler_df['is_wicket'] == 1) & (bowler_df.dismissal_kind != 'run out')].groupby(['bowler'])['is_wicket'].count().reset_index()
wickets_total.rename(columns={'is_wicket': 'total_wickets'}, inplace=True)

runs_conceded = bowler_df.groupby(['bowler'])['total_runs'].sum().reset_index()

balls_bowled = bowler_df[bowler_df.extras_type.isnull()].groupby(['bowler'])['ball'].count().reset_index()
balls_bowled['overs'] = balls_bowled['ball'] // 6 + (balls_bowled['ball'] % 6) / 10
balls_bowled.rename(columns={'ball': 'total_balls'}, inplace=True)

wickets_runs_balls = pd.merge(wickets_total, runs_conceded, on=['bowler'], how='left')
wickets_runs_balls = pd.merge(wickets_runs_balls, balls_bowled, on=['bowler'], how='left')
wickets_runs_balls['strike_rate'] =  round(wickets_runs_balls['total_runs'] / wickets_runs_balls['total_wickets'], 2)
wickets_runs_balls['economy_rate'] =  round(wickets_runs_balls['total_runs'] / wickets_runs_balls['overs'], 2)

wickets_runs_balls_sorted = wickets_runs_balls.sort_values(by=['total_wickets', 'economy_rate'], ascending=[False, True])
wickets_runs_balls_sorted

bowler  total_wickets  total_runs  total_balls  overs  \
94       YS Chahal            139        3128         2386  397.4   
32        HV Patel             99        2349         1586  264.2   
58  Mohammed Siraj             84        2680         1775  295.5   
69   R Vinay Kumar             72        1850         1285  214.1   
97          Z Khan             50        1349          974  162.2   
..             ...            ...         ...          ...    ...   
66   Parvez Rasool              1         130           83   13.5   
84      TM Dilshan              1         196          119   19.5   
57    Mayank Dagar              1         122           70   11.4   
4        AA Noffke              1          41           23    3.5   
9        AS Joseph              1         123           56    9.2   

    strike_rate  economy_rate  
94        22.50          7.87  
32        23.73          8.89  
58        31.90          9.07  
69        25.69          8.64  
97        26.98          8.32  
..          ...           ...  
66       130.00          9.63  
84       196.00         10.05  
57       122.00         10.70  
4         41.00         11.71  
9        123.00         13.37  

[98 rows x 7 columns]

In [56]:
wickets_total = bowler_df[
    (bowler_df['is_wicket'] == 1) & (bowler_df['dismissal_kind'] != 'run out')
].groupby(['bowler', 'match_id'])['is_wicket'].count().reset_index()
wickets_total.rename(columns={'is_wicket': 'total_wickets'}, inplace=True)

runs_conceded = bowler_df.groupby(['bowler', 'match_id'])['total_runs'].sum().reset_index()

balls_bowled = bowler_df[bowler_df.extras_type.isnull()].groupby(['bowler', 'match_id'])['ball'].count().reset_index()
balls_bowled['overs'] = balls_bowled['ball'] // 6 + (balls_bowled['ball'] % 6) / 10
balls_bowled.rename(columns={'ball': 'total_balls'}, inplace=True)

wickets_runs_balls = pd.merge(wickets_total, runs_conceded, on=['bowler', 'match_id'], how='left')
wickets_runs_balls = pd.merge(wickets_runs_balls, balls_bowled, on=['bowler', 'match_id'], how='left')
wickets_runs_balls['strike_rate'] =  round(wickets_runs_balls['total_runs'] / wickets_runs_balls['total_wickets'], 2)
wickets_runs_balls['economy_rate'] =  round(wickets_runs_balls['total_runs'] / wickets_runs_balls['overs'], 2)

wickets_runs_balls_sorted = wickets_runs_balls.sort_values(by=['total_wickets', 'economy_rate'], ascending=[False, True])
wickets_runs_balls_sorted

bowler  match_id  total_wickets  total_runs  total_balls  overs  \
8        A Kumble    392182              5           6           18    3.0   
509  PWH de Silva   1304100              5          19           23    3.5   
260    JD Unadkat    598054              5          25           24    4.0   
196      HV Patel   1254058              5          27           24    4.0   
623      S Badree   1082602              4          10           23    3.5   
..            ...       ...            ...         ...          ...    ...   
319     KV Sharma   1426290              1          43           17    2.5   
670    TG Southee   1178395              1          28           11    1.5   
313     KV Sharma   1359489              1          50           17    2.5   
89    CJ Anderson   1136579              1          11            5    0.5   
466       P Kumar    336026              1          34           11    1.5   

     strike_rate  economy_rate  
8            1.2          2.00  
509          3.8          5.43  
260          5.0          6.25  
196          5.4          6.75  
623          2.5          2.86  
..           ...           ...  
319         43.0         17.20  
670         28.0         18.67  
313         50.0         20.00  
89          11.0         22.00  
466         34.0         22.67  

[864 rows x 8 columns]